#--- identifies this is yml file
---
name: Checks
# trigger
on: [push]
#jobs to run
jobs:
  #  defining new job to check PR title format
  check-pr-title:
    name: Check PR Title Format
      runs-on: ubuntu-20.04
      steps:
        - name: Check PR Title Format
          run: |
          # Get the Pull Request (PR) title
            title=$(jq '.pull_request.title' "$GITHUB_EVENT_PATH")
            
            # Define the expected format of the PR title
            expected_format="Section [0-9]+: .*"
            
            # Check if the PR title matches the expected format
            if ! [[ $title =~ $expected_format ]]; then
              echo "PR title must be in the format 'Section [number]: [description]'"'
              exit 1
            fi
  #  defining new job
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"